# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noveltag',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='noveltag',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='作品类别'),
        ),
    ]
